services:
  mysql:
    image: mysql:8.0
    container_name: chatapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1997Alon
      MYSQL_DATABASE: chatApp2
      MYSQL_USER: root
      MYSQL_PASSWORD: 1997Alon
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  chatapp:
    build: .
    container_name: chatapp-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chatApp2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1997Alon
    depends_on:
      - mysql

volumes:
  mysql-data:
